// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s1.proto

package node

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_Success        ErrorCode = 0
	ErrorCode_IntegrityError ErrorCode = 1
	ErrorCode_FormatError    ErrorCode = 2
	ErrorCode_NotFound       ErrorCode = 3
	ErrorCode_UnSupported    ErrorCode = 4
	ErrorCode_Expired        ErrorCode = 5
	ErrorCode_IllegalState   ErrorCode = 6
	ErrorCode_Busy           ErrorCode = 14
	ErrorCode_InternalError  ErrorCode = 254
	ErrorCode_Unknown        ErrorCode = 255
)

var ErrorCode_name = map[int32]string{
	0:   "Success",
	1:   "IntegrityError",
	2:   "FormatError",
	3:   "NotFound",
	4:   "UnSupported",
	5:   "Expired",
	6:   "IllegalState",
	14:  "Busy",
	254: "InternalError",
	255: "Unknown",
}

var ErrorCode_value = map[string]int32{
	"Success":        0,
	"IntegrityError": 1,
	"FormatError":    2,
	"NotFound":       3,
	"UnSupported":    4,
	"Expired":        5,
	"IllegalState":   6,
	"Busy":           14,
	"InternalError":  254,
	"Unknown":        255,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{0}
}

// streamed procedures
type Procedure int32

const (
	//ul part
	Procedure_Initiate Procedure = 0
	//dl part
	Procedure_NotifyUpgrade Procedure = 128
)

var Procedure_name = map[int32]string{
	0:   "Initiate",
	128: "NotifyUpgrade",
}

var Procedure_value = map[string]int32{
	"Initiate":      0,
	"NotifyUpgrade": 128,
}

func (x Procedure) String() string {
	return proto.EnumName(Procedure_name, int32(x))
}

func (Procedure) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{1}
}

type VersionInfo struct {
	// module name - version
	Versions             map[string]string `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VersionInfo) Reset()         { *m = VersionInfo{} }
func (m *VersionInfo) String() string { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()    {}
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{0}
}

func (m *VersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionInfo.Unmarshal(m, b)
}
func (m *VersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionInfo.Marshal(b, m, deterministic)
}
func (m *VersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionInfo.Merge(m, src)
}
func (m *VersionInfo) XXX_Size() int {
	return xxx_messageInfo_VersionInfo.Size(m)
}
func (m *VersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VersionInfo proto.InternalMessageInfo

func (m *VersionInfo) GetVersions() map[string]string {
	if m != nil {
		return m.Versions
	}
	return nil
}

type UpgradeInfo struct {
	// module name - url/endpoint
	Endpoints            map[string]string `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpgradeInfo) Reset()         { *m = UpgradeInfo{} }
func (m *UpgradeInfo) String() string { return proto.CompactTextString(m) }
func (*UpgradeInfo) ProtoMessage()    {}
func (*UpgradeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{1}
}

func (m *UpgradeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeInfo.Unmarshal(m, b)
}
func (m *UpgradeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeInfo.Marshal(b, m, deterministic)
}
func (m *UpgradeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeInfo.Merge(m, src)
}
func (m *UpgradeInfo) XXX_Size() int {
	return xxx_messageInfo_UpgradeInfo.Size(m)
}
func (m *UpgradeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeInfo proto.InternalMessageInfo

func (m *UpgradeInfo) GetEndpoints() map[string]string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type ParameterInfo struct {
	// parameter name - value
	Parameters           map[string]*ParameterInfo_Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ParameterInfo) Reset()         { *m = ParameterInfo{} }
func (m *ParameterInfo) String() string { return proto.CompactTextString(m) }
func (*ParameterInfo) ProtoMessage()    {}
func (*ParameterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{2}
}

func (m *ParameterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParameterInfo.Unmarshal(m, b)
}
func (m *ParameterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParameterInfo.Marshal(b, m, deterministic)
}
func (m *ParameterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterInfo.Merge(m, src)
}
func (m *ParameterInfo) XXX_Size() int {
	return xxx_messageInfo_ParameterInfo.Size(m)
}
func (m *ParameterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterInfo proto.InternalMessageInfo

func (m *ParameterInfo) GetParameters() map[string]*ParameterInfo_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ParameterInfo_Parameter struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParameterInfo_Parameter) Reset()         { *m = ParameterInfo_Parameter{} }
func (m *ParameterInfo_Parameter) String() string { return proto.CompactTextString(m) }
func (*ParameterInfo_Parameter) ProtoMessage()    {}
func (*ParameterInfo_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{2, 0}
}

func (m *ParameterInfo_Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParameterInfo_Parameter.Unmarshal(m, b)
}
func (m *ParameterInfo_Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParameterInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *ParameterInfo_Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterInfo_Parameter.Merge(m, src)
}
func (m *ParameterInfo_Parameter) XXX_Size() int {
	return xxx_messageInfo_ParameterInfo_Parameter.Size(m)
}
func (m *ParameterInfo_Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterInfo_Parameter proto.InternalMessageInfo

func (m *ParameterInfo_Parameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ParameterInfo_Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type DeviceInfo struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Vendor               string   `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model                string   `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	CpuInfo              string   `protobuf:"bytes,7,opt,name=cpuInfo,proto3" json:"cpuInfo,omitempty"`
	MemInfo              uint64   `protobuf:"varint,8,opt,name=memInfo,proto3" json:"memInfo,omitempty"`
	Storage              uint64   `protobuf:"varint,9,opt,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{3}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DeviceInfo) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *DeviceInfo) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *DeviceInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeviceInfo) GetCpuInfo() string {
	if m != nil {
		return m.CpuInfo
	}
	return ""
}

func (m *DeviceInfo) GetMemInfo() uint64 {
	if m != nil {
		return m.MemInfo
	}
	return 0
}

func (m *DeviceInfo) GetStorage() uint64 {
	if m != nil {
		return m.Storage
	}
	return 0
}

type Utilization struct {
	CpuRate              uint32   `protobuf:"varint,1,opt,name=cpuRate,proto3" json:"cpuRate,omitempty"`
	MemRate              uint32   `protobuf:"varint,2,opt,name=memRate,proto3" json:"memRate,omitempty"`
	StorageRate          uint32   `protobuf:"varint,3,opt,name=storageRate,proto3" json:"storageRate,omitempty"`
	DiskReadRate         float32  `protobuf:"fixed32,4,opt,name=diskReadRate,proto3" json:"diskReadRate,omitempty"`
	DiskWrtnRate         float32  `protobuf:"fixed32,5,opt,name=diskWrtnRate,proto3" json:"diskWrtnRate,omitempty"`
	NetReadRate          float32  `protobuf:"fixed32,6,opt,name=netReadRate,proto3" json:"netReadRate,omitempty"`
	NetWrtnRate          float32  `protobuf:"fixed32,7,opt,name=netWrtnRate,proto3" json:"netWrtnRate,omitempty"`
	NetworkDelay         uint32   `protobuf:"varint,8,opt,name=networkDelay,proto3" json:"networkDelay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Utilization) Reset()         { *m = Utilization{} }
func (m *Utilization) String() string { return proto.CompactTextString(m) }
func (*Utilization) ProtoMessage()    {}
func (*Utilization) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{4}
}

func (m *Utilization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Utilization.Unmarshal(m, b)
}
func (m *Utilization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Utilization.Marshal(b, m, deterministic)
}
func (m *Utilization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Utilization.Merge(m, src)
}
func (m *Utilization) XXX_Size() int {
	return xxx_messageInfo_Utilization.Size(m)
}
func (m *Utilization) XXX_DiscardUnknown() {
	xxx_messageInfo_Utilization.DiscardUnknown(m)
}

var xxx_messageInfo_Utilization proto.InternalMessageInfo

func (m *Utilization) GetCpuRate() uint32 {
	if m != nil {
		return m.CpuRate
	}
	return 0
}

func (m *Utilization) GetMemRate() uint32 {
	if m != nil {
		return m.MemRate
	}
	return 0
}

func (m *Utilization) GetStorageRate() uint32 {
	if m != nil {
		return m.StorageRate
	}
	return 0
}

func (m *Utilization) GetDiskReadRate() float32 {
	if m != nil {
		return m.DiskReadRate
	}
	return 0
}

func (m *Utilization) GetDiskWrtnRate() float32 {
	if m != nil {
		return m.DiskWrtnRate
	}
	return 0
}

func (m *Utilization) GetNetReadRate() float32 {
	if m != nil {
		return m.NetReadRate
	}
	return 0
}

func (m *Utilization) GetNetWrtnRate() float32 {
	if m != nil {
		return m.NetWrtnRate
	}
	return 0
}

func (m *Utilization) GetNetworkDelay() uint32 {
	if m != nil {
		return m.NetworkDelay
	}
	return 0
}

type SignUpReq struct {
	Alg                  uint32   `protobuf:"varint,1,opt,name=alg,proto3" json:"alg,omitempty"`
	Hid                  string   `protobuf:"bytes,2,opt,name=hid,proto3" json:"hid,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp            uint64   `protobuf:"fixed64,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{5}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *SignUpReq) GetHid() string {
	if m != nil {
		return m.Hid
	}
	return ""
}

func (m *SignUpReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SignUpReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type SignUpRsp struct {
	Alg                  uint32   `protobuf:"varint,1,opt,name=alg,proto3" json:"alg,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Expire               uint64   `protobuf:"fixed64,4,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRsp) Reset()         { *m = SignUpRsp{} }
func (m *SignUpRsp) String() string { return proto.CompactTextString(m) }
func (*SignUpRsp) ProtoMessage()    {}
func (*SignUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{6}
}

func (m *SignUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRsp.Unmarshal(m, b)
}
func (m *SignUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRsp.Marshal(b, m, deterministic)
}
func (m *SignUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRsp.Merge(m, src)
}
func (m *SignUpRsp) XXX_Size() int {
	return xxx_messageInfo_SignUpRsp.Size(m)
}
func (m *SignUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRsp proto.InternalMessageInfo

func (m *SignUpRsp) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *SignUpRsp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SignUpRsp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SignUpRsp) GetExpire() uint64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

// pdu for sign in
type SignInReq struct {
	SoftwareVersion      string         `protobuf:"bytes,1,opt,name=softwareVersion,proto3" json:"softwareVersion,omitempty"`
	ProtocolVersion      string         `protobuf:"bytes,2,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	Ipv4Address          string         `protobuf:"bytes,3,opt,name=ipv4Address,proto3" json:"ipv4Address,omitempty"`
	DeviceInfo           *DeviceInfo    `protobuf:"bytes,11,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	Utilization          *Utilization   `protobuf:"bytes,12,opt,name=utilization,proto3" json:"utilization,omitempty"`
	VersionInfo          *VersionInfo   `protobuf:"bytes,13,opt,name=versionInfo,proto3" json:"versionInfo,omitempty"`
	ParameterInfo        *ParameterInfo `protobuf:"bytes,14,opt,name=parameterInfo,proto3" json:"parameterInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{7}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetSoftwareVersion() string {
	if m != nil {
		return m.SoftwareVersion
	}
	return ""
}

func (m *SignInReq) GetProtocolVersion() string {
	if m != nil {
		return m.ProtocolVersion
	}
	return ""
}

func (m *SignInReq) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *SignInReq) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *SignInReq) GetUtilization() *Utilization {
	if m != nil {
		return m.Utilization
	}
	return nil
}

func (m *SignInReq) GetVersionInfo() *VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

func (m *SignInReq) GetParameterInfo() *ParameterInfo {
	if m != nil {
		return m.ParameterInfo
	}
	return nil
}

type SignInRsp struct {
	ParameterInfo        *ParameterInfo `protobuf:"bytes,1,opt,name=parameterInfo,proto3" json:"parameterInfo,omitempty"`
	UpgradeInfo          *UpgradeInfo   `protobuf:"bytes,2,opt,name=upgradeInfo,proto3" json:"upgradeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignInRsp) Reset()         { *m = SignInRsp{} }
func (m *SignInRsp) String() string { return proto.CompactTextString(m) }
func (*SignInRsp) ProtoMessage()    {}
func (*SignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{8}
}

func (m *SignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRsp.Unmarshal(m, b)
}
func (m *SignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRsp.Marshal(b, m, deterministic)
}
func (m *SignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRsp.Merge(m, src)
}
func (m *SignInRsp) XXX_Size() int {
	return xxx_messageInfo_SignInRsp.Size(m)
}
func (m *SignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRsp proto.InternalMessageInfo

func (m *SignInRsp) GetParameterInfo() *ParameterInfo {
	if m != nil {
		return m.ParameterInfo
	}
	return nil
}

func (m *SignInRsp) GetUpgradeInfo() *UpgradeInfo {
	if m != nil {
		return m.UpgradeInfo
	}
	return nil
}

type SignOutReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutReq) Reset()         { *m = SignOutReq{} }
func (m *SignOutReq) String() string { return proto.CompactTextString(m) }
func (*SignOutReq) ProtoMessage()    {}
func (*SignOutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{9}
}

func (m *SignOutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutReq.Unmarshal(m, b)
}
func (m *SignOutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutReq.Marshal(b, m, deterministic)
}
func (m *SignOutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutReq.Merge(m, src)
}
func (m *SignOutReq) XXX_Size() int {
	return xxx_messageInfo_SignOutReq.Size(m)
}
func (m *SignOutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutReq proto.InternalMessageInfo

type SignOutRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRsp) Reset()         { *m = SignOutRsp{} }
func (m *SignOutRsp) String() string { return proto.CompactTextString(m) }
func (*SignOutRsp) ProtoMessage()    {}
func (*SignOutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{10}
}

func (m *SignOutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRsp.Unmarshal(m, b)
}
func (m *SignOutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRsp.Marshal(b, m, deterministic)
}
func (m *SignOutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRsp.Merge(m, src)
}
func (m *SignOutRsp) XXX_Size() int {
	return xxx_messageInfo_SignOutRsp.Size(m)
}
func (m *SignOutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRsp proto.InternalMessageInfo

type GetConfigReq struct {
	ParameterInfo        *ParameterInfo `protobuf:"bytes,1,opt,name=parameterInfo,proto3" json:"parameterInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConfigReq) Reset()         { *m = GetConfigReq{} }
func (m *GetConfigReq) String() string { return proto.CompactTextString(m) }
func (*GetConfigReq) ProtoMessage()    {}
func (*GetConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{11}
}

func (m *GetConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReq.Unmarshal(m, b)
}
func (m *GetConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReq.Marshal(b, m, deterministic)
}
func (m *GetConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReq.Merge(m, src)
}
func (m *GetConfigReq) XXX_Size() int {
	return xxx_messageInfo_GetConfigReq.Size(m)
}
func (m *GetConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReq proto.InternalMessageInfo

func (m *GetConfigReq) GetParameterInfo() *ParameterInfo {
	if m != nil {
		return m.ParameterInfo
	}
	return nil
}

type GetConfigRsp struct {
	ParameterInfo        *ParameterInfo `protobuf:"bytes,1,opt,name=parameterInfo,proto3" json:"parameterInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConfigRsp) Reset()         { *m = GetConfigRsp{} }
func (m *GetConfigRsp) String() string { return proto.CompactTextString(m) }
func (*GetConfigRsp) ProtoMessage()    {}
func (*GetConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{12}
}

func (m *GetConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRsp.Unmarshal(m, b)
}
func (m *GetConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRsp.Marshal(b, m, deterministic)
}
func (m *GetConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRsp.Merge(m, src)
}
func (m *GetConfigRsp) XXX_Size() int {
	return xxx_messageInfo_GetConfigRsp.Size(m)
}
func (m *GetConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRsp proto.InternalMessageInfo

func (m *GetConfigRsp) GetParameterInfo() *ParameterInfo {
	if m != nil {
		return m.ParameterInfo
	}
	return nil
}

type CheckUpgradeReq struct {
	VersionInfo          *VersionInfo `protobuf:"bytes,1,opt,name=versionInfo,proto3" json:"versionInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CheckUpgradeReq) Reset()         { *m = CheckUpgradeReq{} }
func (m *CheckUpgradeReq) String() string { return proto.CompactTextString(m) }
func (*CheckUpgradeReq) ProtoMessage()    {}
func (*CheckUpgradeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{13}
}

func (m *CheckUpgradeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUpgradeReq.Unmarshal(m, b)
}
func (m *CheckUpgradeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUpgradeReq.Marshal(b, m, deterministic)
}
func (m *CheckUpgradeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUpgradeReq.Merge(m, src)
}
func (m *CheckUpgradeReq) XXX_Size() int {
	return xxx_messageInfo_CheckUpgradeReq.Size(m)
}
func (m *CheckUpgradeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUpgradeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUpgradeReq proto.InternalMessageInfo

func (m *CheckUpgradeReq) GetVersionInfo() *VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

type CheckUpgradeRsp struct {
	UpgradeInfo          *UpgradeInfo `protobuf:"bytes,1,opt,name=upgradeInfo,proto3" json:"upgradeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CheckUpgradeRsp) Reset()         { *m = CheckUpgradeRsp{} }
func (m *CheckUpgradeRsp) String() string { return proto.CompactTextString(m) }
func (*CheckUpgradeRsp) ProtoMessage()    {}
func (*CheckUpgradeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{14}
}

func (m *CheckUpgradeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUpgradeRsp.Unmarshal(m, b)
}
func (m *CheckUpgradeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUpgradeRsp.Marshal(b, m, deterministic)
}
func (m *CheckUpgradeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUpgradeRsp.Merge(m, src)
}
func (m *CheckUpgradeRsp) XXX_Size() int {
	return xxx_messageInfo_CheckUpgradeRsp.Size(m)
}
func (m *CheckUpgradeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUpgradeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUpgradeRsp proto.InternalMessageInfo

func (m *CheckUpgradeRsp) GetUpgradeInfo() *UpgradeInfo {
	if m != nil {
		return m.UpgradeInfo
	}
	return nil
}

type ReportStatusReq struct {
	SoftwareVersion      string         `protobuf:"bytes,1,opt,name=softwareVersion,proto3" json:"softwareVersion,omitempty"`
	ProtocolVersion      string         `protobuf:"bytes,2,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	Ipv4Address          string         `protobuf:"bytes,3,opt,name=ipv4Address,proto3" json:"ipv4Address,omitempty"`
	DeviceInfo           *DeviceInfo    `protobuf:"bytes,11,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	Utilization          *Utilization   `protobuf:"bytes,12,opt,name=utilization,proto3" json:"utilization,omitempty"`
	VersionInfo          *VersionInfo   `protobuf:"bytes,13,opt,name=versionInfo,proto3" json:"versionInfo,omitempty"`
	ParameterInfo        *ParameterInfo `protobuf:"bytes,14,opt,name=parameterInfo,proto3" json:"parameterInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReportStatusReq) Reset()         { *m = ReportStatusReq{} }
func (m *ReportStatusReq) String() string { return proto.CompactTextString(m) }
func (*ReportStatusReq) ProtoMessage()    {}
func (*ReportStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{15}
}

func (m *ReportStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportStatusReq.Unmarshal(m, b)
}
func (m *ReportStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportStatusReq.Marshal(b, m, deterministic)
}
func (m *ReportStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportStatusReq.Merge(m, src)
}
func (m *ReportStatusReq) XXX_Size() int {
	return xxx_messageInfo_ReportStatusReq.Size(m)
}
func (m *ReportStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReportStatusReq proto.InternalMessageInfo

func (m *ReportStatusReq) GetSoftwareVersion() string {
	if m != nil {
		return m.SoftwareVersion
	}
	return ""
}

func (m *ReportStatusReq) GetProtocolVersion() string {
	if m != nil {
		return m.ProtocolVersion
	}
	return ""
}

func (m *ReportStatusReq) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *ReportStatusReq) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *ReportStatusReq) GetUtilization() *Utilization {
	if m != nil {
		return m.Utilization
	}
	return nil
}

func (m *ReportStatusReq) GetVersionInfo() *VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

func (m *ReportStatusReq) GetParameterInfo() *ParameterInfo {
	if m != nil {
		return m.ParameterInfo
	}
	return nil
}

type UpgradeNotice struct {
	ParameterInfo        *ParameterInfo `protobuf:"bytes,1,opt,name=parameterInfo,proto3" json:"parameterInfo,omitempty"`
	UpgradeInfo          *UpgradeInfo   `protobuf:"bytes,2,opt,name=upgradeInfo,proto3" json:"upgradeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpgradeNotice) Reset()         { *m = UpgradeNotice{} }
func (m *UpgradeNotice) String() string { return proto.CompactTextString(m) }
func (*UpgradeNotice) ProtoMessage()    {}
func (*UpgradeNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{16}
}

func (m *UpgradeNotice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeNotice.Unmarshal(m, b)
}
func (m *UpgradeNotice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeNotice.Marshal(b, m, deterministic)
}
func (m *UpgradeNotice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeNotice.Merge(m, src)
}
func (m *UpgradeNotice) XXX_Size() int {
	return xxx_messageInfo_UpgradeNotice.Size(m)
}
func (m *UpgradeNotice) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeNotice.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeNotice proto.InternalMessageInfo

func (m *UpgradeNotice) GetParameterInfo() *ParameterInfo {
	if m != nil {
		return m.ParameterInfo
	}
	return nil
}

func (m *UpgradeNotice) GetUpgradeInfo() *UpgradeInfo {
	if m != nil {
		return m.UpgradeInfo
	}
	return nil
}

type StreamMessage struct {
	Proc                 Procedure `protobuf:"varint,1,opt,name=proc,proto3,enum=node.Procedure" json:"proc,omitempty"`
	Code                 ErrorCode `protobuf:"varint,2,opt,name=code,proto3,enum=node.ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StreamMessage) Reset()         { *m = StreamMessage{} }
func (m *StreamMessage) String() string { return proto.CompactTextString(m) }
func (*StreamMessage) ProtoMessage()    {}
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab3478e529997349, []int{17}
}

func (m *StreamMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMessage.Unmarshal(m, b)
}
func (m *StreamMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMessage.Marshal(b, m, deterministic)
}
func (m *StreamMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMessage.Merge(m, src)
}
func (m *StreamMessage) XXX_Size() int {
	return xxx_messageInfo_StreamMessage.Size(m)
}
func (m *StreamMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMessage proto.InternalMessageInfo

func (m *StreamMessage) GetProc() Procedure {
	if m != nil {
		return m.Proc
	}
	return Procedure_Initiate
}

func (m *StreamMessage) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_Success
}

func init() {
	proto.RegisterEnum("node.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("node.Procedure", Procedure_name, Procedure_value)
	proto.RegisterType((*VersionInfo)(nil), "node.VersionInfo")
	proto.RegisterMapType((map[string]string)(nil), "node.VersionInfo.VersionsEntry")
	proto.RegisterType((*UpgradeInfo)(nil), "node.UpgradeInfo")
	proto.RegisterMapType((map[string]string)(nil), "node.UpgradeInfo.EndpointsEntry")
	proto.RegisterType((*ParameterInfo)(nil), "node.ParameterInfo")
	proto.RegisterMapType((map[string]*ParameterInfo_Parameter)(nil), "node.ParameterInfo.ParametersEntry")
	proto.RegisterType((*ParameterInfo_Parameter)(nil), "node.ParameterInfo.Parameter")
	proto.RegisterType((*DeviceInfo)(nil), "node.DeviceInfo")
	proto.RegisterType((*Utilization)(nil), "node.Utilization")
	proto.RegisterType((*SignUpReq)(nil), "node.SignUpReq")
	proto.RegisterType((*SignUpRsp)(nil), "node.SignUpRsp")
	proto.RegisterType((*SignInReq)(nil), "node.SignInReq")
	proto.RegisterType((*SignInRsp)(nil), "node.SignInRsp")
	proto.RegisterType((*SignOutReq)(nil), "node.SignOutReq")
	proto.RegisterType((*SignOutRsp)(nil), "node.SignOutRsp")
	proto.RegisterType((*GetConfigReq)(nil), "node.GetConfigReq")
	proto.RegisterType((*GetConfigRsp)(nil), "node.GetConfigRsp")
	proto.RegisterType((*CheckUpgradeReq)(nil), "node.CheckUpgradeReq")
	proto.RegisterType((*CheckUpgradeRsp)(nil), "node.CheckUpgradeRsp")
	proto.RegisterType((*ReportStatusReq)(nil), "node.ReportStatusReq")
	proto.RegisterType((*UpgradeNotice)(nil), "node.UpgradeNotice")
	proto.RegisterType((*StreamMessage)(nil), "node.StreamMessage")
}

func init() {
	proto.RegisterFile("s1.proto", fileDescriptor_ab3478e529997349)
}

var fileDescriptor_ab3478e529997349 = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4b, 0x6f, 0x23, 0x45,
	0x10, 0x66, 0x6c, 0xc7, 0x8e, 0xcb, 0xaf, 0xd9, 0x06, 0xa2, 0x91, 0x01, 0x11, 0xcd, 0x5e, 0xa2,
	0x48, 0xeb, 0xcd, 0x26, 0x20, 0x1e, 0x8b, 0x56, 0x82, 0x6c, 0x82, 0x7c, 0x60, 0x41, 0x63, 0xc2,
	0x0a, 0x09, 0x09, 0xcd, 0x7a, 0xca, 0xde, 0x51, 0xec, 0xee, 0xde, 0xee, 0xb6, 0x83, 0xe1, 0x00,
	0x37, 0x0e, 0x1c, 0xf9, 0x11, 0xfc, 0x03, 0x6e, 0xfc, 0x0f, 0x4e, 0xdc, 0xf9, 0x13, 0x80, 0xfa,
	0x31, 0x0f, 0x3b, 0x16, 0x0a, 0x0f, 0x71, 0xe2, 0x36, 0xf5, 0xd5, 0xd7, 0x55, 0x5f, 0xd7, 0x54,
	0xd5, 0x0c, 0xec, 0xca, 0x7b, 0x03, 0x2e, 0x98, 0x62, 0xa4, 0x46, 0x59, 0x82, 0xfd, 0x97, 0xa6,
	0x8c, 0x4d, 0x67, 0x78, 0xd7, 0x60, 0x4f, 0x16, 0x93, 0xbb, 0x38, 0xe7, 0x6a, 0x65, 0x29, 0xe1,
	0xb7, 0x1e, 0xb4, 0x3e, 0x41, 0x21, 0x53, 0x46, 0x87, 0x74, 0xc2, 0xc8, 0x7d, 0xd8, 0x5d, 0x5a,
	0x53, 0x06, 0xde, 0x7e, 0xf5, 0xa0, 0x75, 0xfc, 0xea, 0x40, 0x47, 0x19, 0x94, 0x48, 0xd9, 0xb3,
	0x3c, 0xa3, 0x4a, 0xac, 0xa2, 0xfc, 0x40, 0xff, 0x3e, 0x74, 0xd6, 0x5c, 0xc4, 0x87, 0xea, 0x25,
	0xae, 0x02, 0x6f, 0xdf, 0x3b, 0x68, 0x46, 0xfa, 0x91, 0xbc, 0x00, 0x3b, 0xcb, 0x78, 0xb6, 0xc0,
	0xa0, 0x62, 0x30, 0x6b, 0xbc, 0x5d, 0x79, 0xd3, 0x0b, 0xbf, 0xf3, 0xa0, 0x75, 0xc1, 0xa7, 0x22,
	0x4e, 0xd0, 0x28, 0x79, 0x00, 0x4d, 0xa4, 0x09, 0x67, 0x29, 0x55, 0x99, 0x94, 0x7d, 0x2b, 0xa5,
	0xc4, 0x1a, 0x9c, 0x65, 0x14, 0xab, 0xa5, 0x38, 0xd2, 0x7f, 0x07, 0xba, 0xeb, 0xce, 0xbf, 0xa4,
	0xe6, 0x57, 0x0f, 0x3a, 0x1f, 0xc5, 0x22, 0x9e, 0xa3, 0x42, 0x61, 0xf4, 0x9c, 0x02, 0xf0, 0x0c,
	0xc8, 0x04, 0xdd, 0xb6, 0x82, 0xd6, 0x88, 0x85, 0xe5, 0x34, 0x95, 0x8e, 0xf5, 0x5f, 0x87, 0x66,
	0xee, 0x26, 0x04, 0x6a, 0x6a, 0xc5, 0xd1, 0x09, 0x32, 0xcf, 0xdb, 0x15, 0xf5, 0x3f, 0x83, 0xde,
	0x46, 0xd4, 0x2d, 0x97, 0x39, 0x29, 0x1f, 0x6d, 0x1d, 0xbf, 0xf2, 0xa7, 0xda, 0xca, 0x77, 0xfd,
	0xd1, 0x03, 0x78, 0x88, 0xcb, 0x74, 0x6c, 0x0b, 0x5f, 0x96, 0xd5, 0x71, 0xb2, 0xf6, 0xa0, 0xbe,
	0x44, 0x9a, 0x30, 0xe1, 0x74, 0x39, 0x4b, 0xcb, 0x9d, 0xb3, 0x04, 0x67, 0x41, 0xd5, 0xca, 0x35,
	0x06, 0x09, 0xa0, 0xe1, 0x7a, 0x22, 0xa8, 0x19, 0x3c, 0x33, 0xb5, 0x67, 0xcc, 0x17, 0x3a, 0x4d,
	0xd0, 0xb0, 0x1e, 0x67, 0x6a, 0xcf, 0x1c, 0xe7, 0xc6, 0xb3, 0xbb, 0xef, 0x1d, 0xd4, 0xa2, 0xcc,
	0xd4, 0x1e, 0xa9, 0x98, 0x88, 0xa7, 0x18, 0x34, 0xad, 0xc7, 0x99, 0xe1, 0xf7, 0x15, 0x68, 0x5d,
	0xa8, 0x74, 0x96, 0x7e, 0x19, 0xab, 0x22, 0x7a, 0x14, 0xab, 0x4c, 0x7c, 0x66, 0xba, 0xe8, 0xc6,
	0x53, 0xb1, 0x1e, 0x67, 0x92, 0x7d, 0x68, 0xb9, 0x70, 0xc6, 0x5b, 0x35, 0xde, 0x32, 0x44, 0x42,
	0x68, 0x27, 0xa9, 0xbc, 0x8c, 0x30, 0x4e, 0x0c, 0x45, 0x5f, 0xa9, 0x12, 0xad, 0x61, 0x19, 0xe7,
	0xb1, 0x50, 0xd4, 0x70, 0x76, 0x0a, 0x4e, 0x86, 0xe9, 0x4c, 0x14, 0x55, 0x1e, 0xa6, 0x6e, 0x28,
	0x65, 0xc8, 0x31, 0xf2, 0x20, 0x8d, 0x9c, 0x91, 0xc7, 0x08, 0xa1, 0x4d, 0x51, 0x5d, 0x31, 0x71,
	0xf9, 0x10, 0x67, 0xf1, 0xca, 0x94, 0xaa, 0x13, 0xad, 0x61, 0xe1, 0xe7, 0xd0, 0x1c, 0xa5, 0x53,
	0x7a, 0xc1, 0x23, 0x7c, 0xa6, 0xdb, 0x24, 0x9e, 0x4d, 0x5d, 0x39, 0xf4, 0xa3, 0x46, 0x9e, 0xa6,
	0x89, 0x7b, 0x8f, 0xfa, 0x31, 0x6b, 0xa5, 0x6a, 0xd1, 0x4a, 0x2f, 0x43, 0x53, 0xa5, 0x73, 0x94,
	0x2a, 0x9e, 0x73, 0x73, 0xdf, 0x7a, 0x54, 0x00, 0xe1, 0xe3, 0x3c, 0x81, 0xe4, 0x5b, 0x12, 0x74,
	0xa1, 0x92, 0xc7, 0xaf, 0x6c, 0x0d, 0xbf, 0x07, 0x75, 0xfc, 0x82, 0xa7, 0x02, 0x5d, 0x6c, 0x67,
	0x85, 0x3f, 0x57, 0x6c, 0xe4, 0x21, 0xd5, 0xd2, 0x0f, 0xa0, 0x27, 0xd9, 0x44, 0x5d, 0xc5, 0x02,
	0xdd, 0x56, 0x71, 0xdd, 0xbe, 0x09, 0x6b, 0xa6, 0xd9, 0x66, 0x63, 0x36, 0xcb, 0x98, 0x36, 0xfd,
	0x26, 0xac, 0x2b, 0x9c, 0xf2, 0xe5, 0x6b, 0xef, 0x26, 0x89, 0x40, 0x29, 0x9d, 0xa6, 0x32, 0x44,
	0x8e, 0x00, 0x92, 0x7c, 0x16, 0x82, 0x96, 0x19, 0x25, 0xdf, 0x8e, 0x52, 0x31, 0x23, 0x51, 0x89,
	0x43, 0x4e, 0xa0, 0xb5, 0x28, 0x9a, 0x30, 0x68, 0x9b, 0x23, 0xb7, 0xdc, 0xaa, 0x2a, 0x1c, 0x51,
	0x99, 0xa5, 0x0f, 0x2d, 0x8b, 0x8d, 0x1a, 0x74, 0xca, 0x87, 0x4a, 0xab, 0x36, 0x2a, 0xb3, 0xc8,
	0x5b, 0xd0, 0xe1, 0xe5, 0x71, 0x0e, 0xba, 0xe6, 0xd8, 0xf3, 0x5b, 0x26, 0x3d, 0x5a, 0x67, 0x86,
	0x5f, 0xe5, 0x95, 0x95, 0xfc, 0x7a, 0x1c, 0xef, 0xa6, 0x71, 0xcc, 0x65, 0x8b, 0xf5, 0xeb, 0x56,
	0xcd, 0xad, 0x6b, 0x7b, 0x39, 0x2a, 0xb3, 0xc2, 0x36, 0x80, 0x4e, 0xfe, 0xe1, 0x42, 0x45, 0xf8,
	0xac, 0x6c, 0x49, 0x1e, 0x0e, 0xa1, 0xfd, 0x3e, 0xaa, 0x53, 0x46, 0x27, 0xe9, 0x54, 0xbf, 0xf5,
	0xbf, 0xaf, 0x6d, 0x3d, 0xd4, 0x3f, 0xba, 0x66, 0x78, 0x0e, 0xbd, 0xd3, 0xa7, 0x38, 0xbe, 0x74,
	0x57, 0xd2, 0xc2, 0x36, 0xde, 0x98, 0x77, 0x93, 0x37, 0x76, 0x2d, 0x8e, 0xe4, 0x9b, 0x15, 0xf4,
	0x6e, 0x54, 0xc1, 0x5f, 0x2a, 0xd0, 0x8b, 0x90, 0x33, 0xa1, 0x46, 0x2a, 0x56, 0x0b, 0xf9, 0xff,
	0x7c, 0xfc, 0xcb, 0xf3, 0xf1, 0x35, 0x74, 0x5c, 0xf1, 0x1f, 0x31, 0x95, 0x8e, 0xf1, 0x3f, 0x9f,
	0x91, 0x4f, 0xa1, 0x33, 0x52, 0x02, 0xe3, 0xf9, 0x07, 0x28, 0x65, 0x3c, 0x45, 0x72, 0x1b, 0x6a,
	0x5c, 0xb0, 0xb1, 0xc9, 0xdb, 0x3d, 0xee, 0xb9, 0xbc, 0x82, 0x8d, 0x31, 0x59, 0x08, 0x8c, 0x8c,
	0x53, 0x93, 0xc6, 0x2c, 0xb1, 0x1f, 0xb5, 0x9c, 0x74, 0x26, 0x04, 0x13, 0xa7, 0x2c, 0xc1, 0xc8,
	0x38, 0x0f, 0x7f, 0xf0, 0xa0, 0x99, 0x63, 0xa4, 0x05, 0x8d, 0xd1, 0x62, 0x3c, 0x46, 0x29, 0xfd,
	0xe7, 0x08, 0x81, 0xee, 0x90, 0x2a, 0x9c, 0x8a, 0x54, 0xad, 0x0c, 0xc5, 0xf7, 0x48, 0x0f, 0x5a,
	0xe7, 0x4c, 0xcc, 0x63, 0x65, 0x81, 0x0a, 0x69, 0xc3, 0xee, 0x23, 0xa6, 0xce, 0xd9, 0x82, 0x26,
	0x7e, 0x55, 0xbb, 0x2f, 0xe8, 0x68, 0xc1, 0x75, 0x33, 0x62, 0xe2, 0xd7, 0x74, 0xc0, 0x33, 0xb3,
	0xbf, 0x13, 0x7f, 0x87, 0xf8, 0xd0, 0x1e, 0xce, 0x66, 0x38, 0x8d, 0x67, 0xba, 0x51, 0xd1, 0xaf,
	0x93, 0x5d, 0xa8, 0xbd, 0xb7, 0x90, 0x2b, 0xbf, 0x4b, 0x08, 0x74, 0x74, 0x32, 0x41, 0xe3, 0x99,
	0x0d, 0xfd, 0x9b, 0x47, 0xda, 0xd0, 0xb8, 0xa0, 0x97, 0x94, 0x5d, 0x51, 0xff, 0x77, 0xef, 0xf0,
	0x0e, 0x34, 0xf3, 0x1b, 0xea, 0xb4, 0x43, 0x9a, 0xaa, 0x54, 0x87, 0xd1, 0x4a, 0x3b, 0xfa, 0xcd,
	0x4c, 0x56, 0xae, 0x82, 0xfe, 0x37, 0xde, 0xf1, 0x4f, 0xfa, 0x7b, 0x71, 0x6f, 0x84, 0x42, 0xf7,
	0x1a, 0x39, 0x84, 0xba, 0xfd, 0x2c, 0x11, 0x57, 0x87, 0xfc, 0x2b, 0xd8, 0x5f, 0x07, 0x24, 0xcf,
	0xb8, 0x43, 0x5a, 0xe6, 0x9a, 0xcf, 0x4e, 0x7f, 0x1d, 0x90, 0x9c, 0xdc, 0x81, 0x86, 0xdb, 0x57,
	0xc4, 0x2f, 0x7c, 0x76, 0x99, 0xf5, 0x37, 0x10, 0xc9, 0xc9, 0x1b, 0x50, 0xb7, 0x93, 0x4a, 0x5e,
	0xb4, 0xbe, 0x8d, 0xb9, 0xed, 0xef, 0x0d, 0xec, 0x0f, 0xf9, 0x20, 0xfb, 0x21, 0x1f, 0x9c, 0xe9,
	0x1f, 0x72, 0x72, 0x04, 0x75, 0xbb, 0xbb, 0x08, 0xb1, 0x07, 0xcb, 0x7b, 0xb1, 0x7f, 0x0d, 0x93,
	0x9c, 0x3c, 0x80, 0xae, 0xed, 0x99, 0x8f, 0x45, 0x4c, 0xe5, 0x04, 0x05, 0x71, 0xed, 0xb9, 0xd6,
	0x49, 0xfd, 0x6d, 0xe0, 0x81, 0x77, 0xe4, 0x3d, 0xa9, 0x1b, 0x05, 0x27, 0x7f, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xc4, 0x46, 0x37, 0x94, 0x32, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// S1ServiceClient is the client API for S1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type S1ServiceClient interface {
	// agent-initiated unidirectional services
	SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpRsp, error)
	SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInRsp, error)
	SignOut(ctx context.Context, in *SignOutReq, opts ...grpc.CallOption) (*SignOutRsp, error)
	Report(ctx context.Context, in *ReportStatusReq, opts ...grpc.CallOption) (*empty.Empty, error)
	Config(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigRsp, error)
	// agent-initiated bidirectional service
	StreamTransfer(ctx context.Context, opts ...grpc.CallOption) (S1Service_StreamTransferClient, error)
}

type s1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewS1ServiceClient(cc grpc.ClientConnInterface) S1ServiceClient {
	return &s1ServiceClient{cc}
}

func (c *s1ServiceClient) SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpRsp, error) {
	out := new(SignUpRsp)
	err := c.cc.Invoke(ctx, "/node.S1Service/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s1ServiceClient) SignIn(ctx context.Context, in *SignInReq, opts ...grpc.CallOption) (*SignInRsp, error) {
	out := new(SignInRsp)
	err := c.cc.Invoke(ctx, "/node.S1Service/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s1ServiceClient) SignOut(ctx context.Context, in *SignOutReq, opts ...grpc.CallOption) (*SignOutRsp, error) {
	out := new(SignOutRsp)
	err := c.cc.Invoke(ctx, "/node.S1Service/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s1ServiceClient) Report(ctx context.Context, in *ReportStatusReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/node.S1Service/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s1ServiceClient) Config(ctx context.Context, in *GetConfigReq, opts ...grpc.CallOption) (*GetConfigRsp, error) {
	out := new(GetConfigRsp)
	err := c.cc.Invoke(ctx, "/node.S1Service/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s1ServiceClient) StreamTransfer(ctx context.Context, opts ...grpc.CallOption) (S1Service_StreamTransferClient, error) {
	stream, err := c.cc.NewStream(ctx, &_S1Service_serviceDesc.Streams[0], "/node.S1Service/StreamTransfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &s1ServiceStreamTransferClient{stream}
	return x, nil
}

type S1Service_StreamTransferClient interface {
	Send(*StreamMessage) error
	Recv() (*StreamMessage, error)
	grpc.ClientStream
}

type s1ServiceStreamTransferClient struct {
	grpc.ClientStream
}

func (x *s1ServiceStreamTransferClient) Send(m *StreamMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *s1ServiceStreamTransferClient) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// S1ServiceServer is the server API for S1Service service.
type S1ServiceServer interface {
	// agent-initiated unidirectional services
	SignUp(context.Context, *SignUpReq) (*SignUpRsp, error)
	SignIn(context.Context, *SignInReq) (*SignInRsp, error)
	SignOut(context.Context, *SignOutReq) (*SignOutRsp, error)
	Report(context.Context, *ReportStatusReq) (*empty.Empty, error)
	Config(context.Context, *GetConfigReq) (*GetConfigRsp, error)
	// agent-initiated bidirectional service
	StreamTransfer(S1Service_StreamTransferServer) error
}

// UnimplementedS1ServiceServer can be embedded to have forward compatible implementations.
type UnimplementedS1ServiceServer struct {
}

func (*UnimplementedS1ServiceServer) SignUp(ctx context.Context, req *SignUpReq) (*SignUpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedS1ServiceServer) SignIn(ctx context.Context, req *SignInReq) (*SignInRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedS1ServiceServer) SignOut(ctx context.Context, req *SignOutReq) (*SignOutRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (*UnimplementedS1ServiceServer) Report(ctx context.Context, req *ReportStatusReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (*UnimplementedS1ServiceServer) Config(ctx context.Context, req *GetConfigReq) (*GetConfigRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (*UnimplementedS1ServiceServer) StreamTransfer(srv S1Service_StreamTransferServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTransfer not implemented")
}

func RegisterS1ServiceServer(s *grpc.Server, srv S1ServiceServer) {
	s.RegisterService(&_S1Service_serviceDesc, srv)
}

func _S1Service_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S1ServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.S1Service/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S1ServiceServer).SignUp(ctx, req.(*SignUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _S1Service_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S1ServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.S1Service/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S1ServiceServer).SignIn(ctx, req.(*SignInReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _S1Service_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S1ServiceServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.S1Service/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S1ServiceServer).SignOut(ctx, req.(*SignOutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _S1Service_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S1ServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.S1Service/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S1ServiceServer).Report(ctx, req.(*ReportStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _S1Service_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S1ServiceServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.S1Service/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S1ServiceServer).Config(ctx, req.(*GetConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _S1Service_StreamTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(S1ServiceServer).StreamTransfer(&s1ServiceStreamTransferServer{stream})
}

type S1Service_StreamTransferServer interface {
	Send(*StreamMessage) error
	Recv() (*StreamMessage, error)
	grpc.ServerStream
}

type s1ServiceStreamTransferServer struct {
	grpc.ServerStream
}

func (x *s1ServiceStreamTransferServer) Send(m *StreamMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *s1ServiceStreamTransferServer) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _S1Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "node.S1Service",
	HandlerType: (*S1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _S1Service_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _S1Service_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _S1Service_SignOut_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _S1Service_Report_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _S1Service_Config_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTransfer",
			Handler:       _S1Service_StreamTransfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "s1.proto",
}
